INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ();

INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();
INSERT INTO users (name, age) VALUES ();

INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
INSERT INTO pledges (amount, user_id, project_id) VALUES ();
